name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        features:
          - "common-utils"
          - "go"
          - "hugo"
        baseImage:
          - "ubuntu:22.04"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install latest devcontainer CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'
        run: |
          devcontainer features test . -f ${{ matrix.features }} -i ${{ matrix.baseImage }}
